### ISSUE TITLE
Parsing synchronously

### ISSUE THREAD

**Issue by raine** [jsdoc2md/jsdoc-parse#13]
Is there any conceivable way to parse JSDoc synchronously?

I've tried `child_process.execSync` with the jsdoc binary without luck. The JSON output is just cut off, too big I guess?

My use case is extending a module at runtime so that when it's read, the JSDoc documentation is parsed and used. Currently I do the parsing in npm `postinstall` script but I'd like to move it to runtime and cache the result.

Appreciate any ideas!

**Comment by 75lb** [comment]
it doesn't work with `execSync`? i didn't know - i haven't tried it yet.. i do plan to add a sync option in the future but the default behaviour will remain async (to keep compatibility with 0.10 and earlier).

> Is there any conceivable way to parse JSDoc synchronously?

isn't this an issue for the jsdoc project? Personally, i don't know.. yet.

**Comment by 75lb** [comment]
hi, i just tried `execSync` and it works.. so i will be using this to implement a synchronous interface in jsdoc-parse v2 :+1: 

```
const execSync = require('child_process').execSync
const output = execSync('jsdoc -X class.js', { encoding: 'utf8' })

console.log(output)
// outputs JSON
```
