### ISSUE TITLE
es6 class instance properties not documented when class is part of @module

### ISSUE THREAD

**Issue by 75lb** [jsdoc2md/jsdoc-parse#16]
in the example below `something.whatever` is not documented.. remove the `@module` declaration and it outputs correctly. 

```js
/**
 * @module something
 */

/**
 * create something
 */
class Something {
  constructor () {
    /**
     * a value
     * @type {number}
     */
    this.whatever = 1
  }
}
```

**Comment by knrdhz** [comment]
Hello,

this seems to be an unresolved issue. Generating doc for TypeScript is constantly ignoring class properties (unless they are mixed with the class methods) when the class is decorated with @module declaration. Anyone having the same issue?
