### ISSUE TITLE
Doesn't seem to be passing config file

### ISSUE THREAD

**Issue by nathanmarks** [jsdoc2md/jsdoc-parse#20]
Doesn't seem to be passing the user config file. 

I added this to line 48 of `jsdoc-parse.js` on my fork as a temp fix:

```js
  else if (options.conf) jsdocOptions.configure = options.conf
```

I'd do a PR but I'm not sure how you want to handle priority/merging of configs in the case that someone passes their own config and the html option.

**Comment by 75lb** [comment]
fixed and released in jsdoc-parse v1.2.7, thanks for letting me know!
