### ISSUE TITLE
Enhancement: Support way of hooking into transform

### ISSUE THREAD

**Issue by catesandrew** [jsdoc2md/jsdoc-parse#21]
I have a few use cases for this functionality. The first is that I document my jsdoc params with the optional hyphen `-`, between the name and description. This results in double hyphens being output since there's a hyphen in the hbs template. Now the template can check if there is a hyphen or not before outputting it or I could easily do the logic in the code, which I prefer for this use case. Oh, here's an example of such a param, `* @param {Object} employee - The employee who is responsible for the project.`

```js
function cleanParams (identifier) {
  if (identifier.params) {
    identifier.params = identifier.params.map(function (param) {
      if (param.description)
        param.description = param.description.replace(/(?:^- )/g, '')
      return param
    })
  }
  return identifier
}

// then make call to cleanParams from with the transform function
function transform () {
  return collectJson(data => {

    json = json.map(function (identifier) {
      identifier = cleanParams(identifier)
      return identifier
    })
  })
}
```

I also wanted to not hard wrap the final markdown. The comments in my code were wrapped to the 80th column and could span a few or more lines. The end result is that [transform](https://github.com/jsdoc2md/jsdoc-parse/blob/master/lib/transform.js) sees a lot of `\n` in the description.

So I quickly hacked isac's [json-stringify-safe](https://github.com/isaacs/json-stringify-safe) code, added a call to it from transform like this:

```js
function transform () {
  return collectJson(data => {
    data = fixConstructorMemberLongnames(data)

    json = JSON.parse(stringify(json, 2))

    json = json.map(function (identifier) {
      return identifier
    })

    return JSON.stringify(json, null, '  ')
  })
}
``` 

Here's the ugly hack i threw together, just in case, you were interested. It recursively iterates through the json object returned from jsdoc, looks for whitelisted keys, and then removes the newlines from them. 

```js
function stringify(obj, spaces, cycleReplacer) {
  return JSON.stringify(obj, serializer(cycleReplacer), spaces)
}

function serializer(cycleReplacer) {
  return function(key, value) {
    if (!value) return value

    if (typeof(value) === 'string' ) {
      // todo: don't want to remove these newlines though:
      //\n * -
      if (key === 'description')
        value = value.replace(/(?:\r\n|\r|\n)/g, ' ')
    } else if (value.length) {
      if (key === 'see' || key === 'todo') {
        value = value.map(function (val) {
          if (typeof(val)==='string')
            return val.replace(/(?:\r\n|\r|\n)/g, ' ')
          return val
        })
      }
    }

    return value
  }
}
```

**Comment by 75lb** [comment]
hi.. i think this is more an issue for dmd.. no formatting shuold happen in jsdoc-parse, it merely collects values to be formatted by dmd.. 

however, hooking into the transform step is being considered for jsdoc2md v2 (in progress).. although strictly speaking it should not be necessary as the output from jsdoc & jsdoc-parse is just template data for something else to format. 

Closing this as [dmd is already extensible](https://github.com/jsdoc2md/dmd#customising), so tweaks to the output should not need code changes.

**Comment by catesandrew** [comment]
using partials, got it, thanks!
