### ISSUE TITLE
parsing html comments

### ISSUE THREAD

**Issue by jaichandra** [jsdoc2md/jsdoc-parse#22]
Being able to parse html pages is a great feature. I believe I can use this to parse handlebars files for documentation. But can this library parse `<!-- -->` comments as well? What would be the effort if we need to add that support?

Thanks

**Comment by 75lb** [comment]
hi, i apologise for the late reply! What do you mean by can it parse `<!-- -->` comments? Can you post an example of source code you need to parse?
