### ISSUE TITLE
Please update npm with latest

### ISSUE THREAD

**Issue by valedaemon** [jsdoc2md/jsdoc-parse#26]
v1.2.7 in npm still references outdated dependencies, several of which currently have security vulnerabilities.

Many thanks!

**Comment by 75lb** [comment]
hi!

yes, when you install jsdoc-parse you see these warnings: 
```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-
```

I will fix the minimatch warning but i can't fix the wrench warning. Wrench is a dependency of jsdoc3 and the issue [has already been reported to them](https://github.com/jsdoc3/jsdoc/issues/1187).

**Comment by 75lb** [comment]
i have fixed the `wrench` warning (by forking and patching jsdoc), will fix minimatch soon too.

**Comment by 75lb** [comment]
all deps now up to date
