### ISSUE TITLE
Upgrading to 2.x.x

### ISSUE THREAD

**Issue by vvo** [jsdoc2md/jsdoc-parse#28]
Hey hi, is there a migration guide or some notes on how to upgrade to 2.x.x and what does it brings? Thanks

**Comment by 75lb** [comment]
i can write one for you tonight but my quickest answer is: use [jsdoc2md.getTemplateData()](https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/docs/API.md#jsdoc2mdgettemplatedataoptions--promise).

This method would return you identical data to what jsdoc-parse v1 returns, with the exception of the `enum` and `@private` changes i mentioned [here](https://github.com/jsdoc2md/jsdoc-parse/releases/tag/v2.0.5)

```js
jsdoc2md.getTemplateDataSync({ files: 'lib/*.js' })

// returns jsdoc-parse data
```

you could use jsdoc-parse v2 alone if you like but it expects raw jsdoc data to be passed in - which you could get using [jsdoc-api](https://github.com/jsdoc2md/jsdoc-api).

**Comment by vvo** [comment]
Thanks! I think that's enough
