### ISSUE TITLE
how can I sort sort the api?

### ISSUE THREAD

**Issue by obedm503** [jsdoc2md/jsdoc-parse#29]
I have some private methods and a public one. I would like the public method to be shown first and then the private methods. By looking into the issues and the commit history it seems there was a `sort-by` (later named `sortBy`) option that was removed (874057da9040ae109e513aaba290acccdac70f93). 

Is this option hidden somewhere? How can I customize the order of my methods?

**Comment by 75lb** [comment]
hi.. well, if you're using the jsdoc-parse module directly you can sort its output with [orderby](https://lodash.com/docs/4.16.6#orderBy)..

or are you suggesting we add the `--sort-by` option back into jsdoc2md?

**Comment by obedm503** [comment]
I´m using  jsdoc2md. So yes, a "sort by" option in jsdoc2md would be nice. Plus, I see no harm in having one.

Thanks for the fast reply.

**Comment by 75lb** [comment]
duplicate of https://github.com/jsdoc2md/jsdoc-to-markdown/issues/101
