### ISSUE TITLE
Support jsdoc plugins

### ISSUE THREAD

**Issue by Rantanen** [jsdoc2md/jsdoc-parse#3]
JSDoc has a configuration file with plugin support. As far as I know there's no way to pass this configuration in through `jsdoc-parse`.

**Comment by 75lb** [comment]
That's true.. which plugin do you need to use?

**Comment by Rantanen** [comment]
summarize

Automatically extracts the start of the description as a `@summary`. Essentially I've got jsdoc2md template that orders the method documentation as:

- Summary
- Params
- Returns
- Description

I like splitting summary and description as the first sentence of summary is should be enough to describe the whole method and you can still include longer description that details the intricacies.

Example: https://github.com/Rantanen/node-mumble/wiki/MumbleWrapper

Though it's so heavily customized that I could probably go and create my own handlebars helper for doing that myself in the handlebar templates.

**Comment by gkourupes** [comment]
Hi,
I would also like to have the ability to pass in a plugin.
I'm using jsdoc2md and I'm working on an angular project.  The guys would like to use @ngdoc as it is used by their IDE (webstorm) so I am hoping to develop some nice custom angular style documentation where @ngdoc is used.  They really want markdown output, so using something like angular-jsdoc isn't an option.

The plugin I'd like to use would most likely be a custom one, or perhaps the one in angular-jsdoc.

Looking forward to your thoughts.

**Comment by 75lb** [comment]
released in jsdoc-parse v1.2 (and jsdoc2md v1.3).. see the `--conf` option.. let me know if you have any more issues!
