### ISSUE TITLE
Constructor documentation is ignored unless description or @param is included

### ISSUE THREAD

**Issue by afsmith92** [jsdoc2md/jsdoc-parse#33]
I ran into [this](https://github.com/jsdoc2md/jsdoc-to-markdown/issues/73) issue where `@example` tags on class docs get ignored if a description (tagless description or `@description` -- not `@classdesc`) is not included.

Based on [this line](https://github.com/jsdoc2md/jsdoc-parse/blob/master/lib/transform.js#L126) the following tags on class docs are associated to the constructor: 
* description
* params
* examples
* returns
* exceptions

However, on [this line](https://github.com/jsdoc2md/jsdoc-parse/blob/master/lib/transform.js#L136) a constructor is only output if it has a description or params. Would it make sense to update this to check for examples, returns, and exceptions as well?

**Comment by afsmith92** [comment]
@75lb Any thoughts on this? I'd be happy to submit a PR.

**Comment by 75lb** [comment]
sorry, I haven't had chance to properly triage it yet..  It's possible the issue stems from the underlying jsdoc, which has seen some project activity recently - i need to catch up and start using the latest version. Feel free to submit a PR if you find a quick fix.

**Comment by 75lb** [comment]
Could you check whether this issue is resolved by [jsdoc2md v5.0.0](https://github.com/jsdoc2md/jsdoc-to-markdown/releases/tag/v5.0.0) please?

**Comment by 75lb** [comment]
PR Merged and released, let me know if there's anything else. Feel free to also test the [jsdocm2d v9 pre-release](https://github.com/jsdoc2md/jsdoc-to-markdown/releases/) if you like.
