### ISSUE TITLE
Resurrect 'sort-by' option

### ISSUE THREAD

**Issue by whitlockjc** [jsdoc2md/jsdoc-parse#36]
I'm just now upgrading from a very old version of `jsdoc-to-markdown` and it seems the `sort-by` option was removed in 1d51ff3f4276cc607ebcba2cde3b1f1177fbff7b.  Is this feature available elsewhere?  If not, can we get it back?

**Comment by 75lb** [comment]
Hi, please see the answer in [this issue](https://github.com/jsdoc2md/jsdoc-to-markdown/issues/101) for a description of how to sort the docs. 

Closing this ticket as a duplicate but leaving the existing one open.
