### ISSUE TITLE
Feature Request: Allow `@private` to show in result set.

### ISSUE THREAD

**Issue by reggi** [jsdoc2md/jsdoc-parse#6]
I need a way of knowing if a module definition is set to `@private`. However the current functionality is that if `@private` is in the `@module` definition then that definition is not in the JSON result set. Ideally each declaration had a `private: true || false` setting. Thoughts?

**Comment by 75lb** [comment]
run jsdoc-parse (or jsdoc2md) with the `--private` option to include private identifiers in the output.. all private items with have the value `"access": "private"`

**Comment by reggi** [comment]
Wow, thanks!
