### ISSUE TITLE
Cannot find module (/node_modules/jsdoc-75lb/jsdoc.js) - npm3

### ISSUE THREAD

**Issue by andrewwakeling** [jsdoc2md/jsdoc-parse#9]
npm3 is still in beta, but I just wanted to create this ticket to raise awareness of the incoming change to the way node_modules are structured with npm3.

In getJsdocOutput (jsdoc-parse.js) it won't be safe to assume that the module will be located in that directory.

**Comment by 75lb** [comment]
Thanks, will look into it..

**Comment by 75lb** [comment]
fixed and released in jsdoc-parse 1.1.0 - thanks for the alert.. 

update/re-install your tool/plugin to pick up the change..

**Comment by andrewwakeling** [comment]
Thank you!
